* Jeannie: Working with RDF in Common Lisp via JSON-LD

<https://bitbucket.org/easye/jeannie/>
<https://gitlab.common-lisp.net/mevenson/jeannie/>
<https://github.com/easye/jeannie/>

** Jeannie

Jeannie provides an encapsulation of Apache Jena in Common Lisp via
direct manipulation of Maven binary POM artifacts via an ~ABCL~
runtime <http://abcl.org>.

** Djini

Djini prototypes scaffolding for transcribing syntaxes represented in
Common Lisp into serialized N3 triples that can then be placed in RDF
stores.  Currently only a prototype for serializing JSOWN object
structures exists in a rudimentary form.  Includes a speculative
DJINI/MODEL/JSON-LD component for round-tripping through Javascript
object notation.

** Installation

1. Add this directory to ASDF.
#+BEGIN_SRC lisp
;;; <file:~/.config/common-lisp/source-registry.conf.d/>
;;; ASDF source registry configuration script
(:directory (:home "work/jeannie/"))
#+END_SRC

2. Install a Common Lisp with Quicklisp.

3. Satisfy the Quicklisp dependencies


~ABCL~
#+BEGIN_SRC 
(ql:quickload :jeannie/test)
#+END_SRC

or 

~SBCL~, ~CCL~, ~ECL~, ~ABCL~
#+BEGIN_SRC 
(ql:quickload :djini/t)

#+END_SRC


** Usage

From the Common Lisp ~REPL~ issue either 

~ABCL~
#+BEGIN_SRC 
(asdf:make :jeannie/test)
(asdf:test-stystem :jeannie)
#+END_SRC

or 

~SBCL~, ~CCL~, ~ECL~, ~ABCL~
#+BEGIN_SRC 
(asdf:make :djini/t)
(asdf:test-stystem :djini)
#+END_SRC

** Bugs

Report via issues at <https://bitbucket.org/easye/jeannie>.

*** Fuseki Embedded doesn't have the nice endpoints

What invoking ```fuseki-server``` boils down to:

*** JSS
#+BEGIN_EXAMPLE
(#"main" 'org.apache.jena.fuseki.cmd.FusekiCmd (java:jarray-from-list '("")))
; Evaluation aborted on #<JAVA-EXCEPTION java.lang.NoClassDefFoundError: org/apache/jena/fuseki/cmd/FusekiCmd$FusekiCmdInner {1AE2263D}>.

#+END_EXAMPLE


**** JAVA
#+BEGIN_EXAMPLE
(java:jstatic "main" "org.apache.jena.fuseki.cmd.FusekiCmd" (java:jarray-from-list '("")))
                  
; Evaluation aborted on #<JAVA-EXCEPTION java.lang.NoClassDefFoundError: org/apache/jena/fuseki/cmd/FusekiCmd$FusekiCmdInner {2CB152D}>.

#+END_EXAMPLE

** Installing artifacts manually
#+BEGIN_EXAMPLE
mvn org.apache.maven.plugins:maven-dependency-plugin:2.1:get \
    -DrepoUrl=http://download.java.net/maven/2/ \
    -Dartifact=robo-guice:robo-guice:0.4-SNAPSHOT
#+END_EXAMPLE

* Colophon
#+BEGIN_EXAMPLE
Mark <evenson.not.org@gmail.com>
Created: 2012-Jan-21 
Revised: <2020-04-20 Mon 13:17>
#+END_EXAMPLE
